apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: learning
  labels:
    app: mongo
type: Opaque
data:
  # echo SECRET_VALUE | base64
  mongo-user: cm9vdCANCg==
  mongo-password: MTIzbmV2ZXIgDQo=
