apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: learning
  labels:
    app: mongo
type: Opaque
data:
  # echo -n "SECRET_VALUE" | base64
  mongo-user: cm9vdA==
  mongo-password: MTIzbmV2ZXI=
