# WEB CLIENT POD

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: learning
  labels:
    app: webapp

# SPECIFICATIONS
spec:
  replicas: 1

  # MATCHING ALL LABELS TO CREATE THESE PODS
  selector:
    matchLabels:
      app: webapp

  # POD
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: nanajanashia/k8s-demo-app
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          
          
          # CREATE ENV VARIABLES
          # DIFFERENT IMAGES FROM THE HUB ARE KNOWN TO HAVE ENV VARIABLES THAT ALLOW THEIR USECASE TO RUN
          env:
            - name: USER_NAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-url
