# WEB CLIENT SERVICE

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: learning
  labels:
    app: webapp

# SPECIFICATIONS
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      # request comes into cluster on 3000
      port: 3000

      # route to database container open port 3000
      targetPort: 3000

      # open on kubernetes nodes to which app is accessable
      nodePort: 30100
