# WEB CLIENT SERVICE

apiVersion: v1
kind: Service
metadata:
  name: webApp-service
  namespace: learning
  labels:
    app: webApp

# SPECIFICATIONS
spec:
  type: NodePort
  selector:
    app: webApp
  ports:
    - protocol: TCP
      # request comes into cluster on 27017
      port: 3000

      # route to database container open port 27017
      targetPort: 3000

      # open on kubernetes nodes to which app is accessable
      nodePort: 30000
