apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: affans-cluster
spec:
  selector:
    app: mongo-express
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30000
