apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: affans-cluster
  labels:
    app: mongo-express
spec:
  replicas: 1

  selector:
    matchLabels:
      app: mongo-express

  # POD
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express

          # MATCH SERVICE PORT
          ports:
            - containerPort: 8081

          # ENVIROMENT VARIABLES
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-root-username

            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-root-password

            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: database_url

          # RESOURCE LIMITATIONS
          resources:
            limits:
              memory: 512Mi
              cpu: "0.5"
            requests:
              memory: 256Mi
              cpu: "0.5"
