apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: affans-cluster

spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      # NEED TO MATCH SERVICE PORT & CONTAINER PORT
      port: 27017
      targetPort: 27017
